# Generated by Django 3.2.9 on 2021-11-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranzactie',
            name='medicament',
            field=models.CharField(default='Paracetamol', max_length=200),
            preserve_default=False,
        ),
    ]
