# Generated by Django 3.2.9 on 2021-11-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacie', '0002_tranzactie_medicament'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='nr_vanzari',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nume',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
