# Generated by Django 3.2.9 on 2021-11-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacie', '0003_auto_20211121_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='nr_vanzari',
        ),
    ]
