# Generated by Django 3.2.9 on 2021-11-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacie', '0004_remove_medicament_nr_vanzari'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='nr_vanzari',
            field=models.IntegerField(default=0),
        ),
    ]
