# Generated by Django 3.2.9 on 2021-11-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacie', '0005_medicament_nr_vanzari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='nr_vanzari',
            field=models.IntegerField(),
        ),
    ]
