# Generated by Django 3.2.9 on 2021-11-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacie', '0007_alter_medicament_nr_vanzari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='nume',
            field=models.CharField(max_length=200),
        ),
    ]
