# Generated by Django 3.2.9 on 2021-12-08 15:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmacie', '0008_alter_medicament_nume'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTranzactie',
            fields=[
                ('id', models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False)),
                ('id_card_client', models.CharField(
                    blank=True,
                    max_length=200,
                    null=True)),
                ('medicament', models.CharField(max_length=200)),
                (
                    'nr_bucati',
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(
                            0)]
                        )
                    ),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                (
                    'history_id',
                    models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                (
                    'history_change_reason',
                    models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(
                        choices=[
                            ('+', 'Created'),
                            ('~', 'Changed'), ('-', 'Deleted')], max_length=1
                        )),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tranzactie',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMedicament',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False)),
                ('nume', models.CharField(max_length=200)),
                ('producator', models.CharField(max_length=200)),
                (
                    'pret',
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(
                            0.0)])),
                ('necesita_reteta', models.BooleanField()),
                ('nr_vanzari', models.IntegerField(default=0)),
                (
                    'history_id',
                    models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                (
                    'history_change_reason',
                    models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[
                        ('+', 'Created'),
                        ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical medicament',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCard_client',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False)),
                ('nume', models.CharField(max_length=200)),
                ('prenume', models.CharField(max_length=200)),
                (
                    'CNP',
                    models.CharField(
                        db_index=True,
                        max_length=13,
                        validators=[django.core.validators.MinLengthValidator(
                            13)])),
                ('data_nasterii', models.DateField()),
                ('data_inregistrarii', models.DateField()),
                (
                    'history_id',
                    models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                (
                    'history_change_reason',
                    models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[
                        ('+', 'Created'),
                        ('~', 'Changed'),
                        ('-', 'Deleted')], max_length=1)),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical card_client',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
